/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as UsersUserIdIndexRouteImport } from './routes/users.$userId.index'
import { Route as UsersUserIdTodosRouteImport } from './routes/users.$userId.todos'
import { Route as UsersUserIdAlbumsIndexRouteImport } from './routes/users.$userId.albums_.index'
import { Route as UsersUserIdPostsPostIdRouteImport } from './routes/users.$userId.posts.$postId'
import { Route as UsersUserIdAlbumsAlbumIdRouteImport } from './routes/users.$userId.albums.$albumId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdTodosRoute = UsersUserIdTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdAlbumsIndexRoute = UsersUserIdAlbumsIndexRouteImport.update({
  id: '/albums_/',
  path: '/albums/',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdPostsPostIdRoute = UsersUserIdPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdAlbumsAlbumIdRoute =
  UsersUserIdAlbumsAlbumIdRouteImport.update({
    id: '/albums/$albumId',
    path: '/albums/$albumId',
    getParentRoute: () => UsersUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users': typeof UsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/': typeof UsersIndexRoute
  '/users/$userId/todos': typeof UsersUserIdTodosRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/users/$userId/albums/$albumId': typeof UsersUserIdAlbumsAlbumIdRoute
  '/users/$userId/posts/$postId': typeof UsersUserIdPostsPostIdRoute
  '/users/$userId/albums': typeof UsersUserIdAlbumsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users': typeof UsersIndexRoute
  '/users/$userId/todos': typeof UsersUserIdTodosRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
  '/users/$userId/albums/$albumId': typeof UsersUserIdAlbumsAlbumIdRoute
  '/users/$userId/posts/$postId': typeof UsersUserIdPostsPostIdRoute
  '/users/$userId/albums': typeof UsersUserIdAlbumsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/users': typeof UsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/': typeof UsersIndexRoute
  '/users/$userId/todos': typeof UsersUserIdTodosRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/users/$userId/albums/$albumId': typeof UsersUserIdAlbumsAlbumIdRoute
  '/users/$userId/posts/$postId': typeof UsersUserIdPostsPostIdRoute
  '/users/$userId/albums_/': typeof UsersUserIdAlbumsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/users/'
    | '/users/$userId/todos'
    | '/users/$userId/'
    | '/users/$userId/albums/$albumId'
    | '/users/$userId/posts/$postId'
    | '/users/$userId/albums'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts/$postId'
    | '/users'
    | '/users/$userId/todos'
    | '/users/$userId'
    | '/users/$userId/albums/$albumId'
    | '/users/$userId/posts/$postId'
    | '/users/$userId/albums'
  id:
    | '__root__'
    | '/'
    | '/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/users/'
    | '/users/$userId/todos'
    | '/users/$userId/'
    | '/users/$userId/albums/$albumId'
    | '/users/$userId/posts/$postId'
    | '/users/$userId/albums_/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersRoute: typeof UsersRouteWithChildren
  PostsPostIdRoute: typeof PostsPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users/$userId/todos': {
      id: '/users/$userId/todos'
      path: '/todos'
      fullPath: '/users/$userId/todos'
      preLoaderRoute: typeof UsersUserIdTodosRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users/$userId/albums_/': {
      id: '/users/$userId/albums_/'
      path: '/albums'
      fullPath: '/users/$userId/albums'
      preLoaderRoute: typeof UsersUserIdAlbumsIndexRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users/$userId/posts/$postId': {
      id: '/users/$userId/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/users/$userId/posts/$postId'
      preLoaderRoute: typeof UsersUserIdPostsPostIdRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users/$userId/albums/$albumId': {
      id: '/users/$userId/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/users/$userId/albums/$albumId'
      preLoaderRoute: typeof UsersUserIdAlbumsAlbumIdRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
  }
}

interface UsersUserIdRouteChildren {
  UsersUserIdTodosRoute: typeof UsersUserIdTodosRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
  UsersUserIdAlbumsAlbumIdRoute: typeof UsersUserIdAlbumsAlbumIdRoute
  UsersUserIdPostsPostIdRoute: typeof UsersUserIdPostsPostIdRoute
  UsersUserIdAlbumsIndexRoute: typeof UsersUserIdAlbumsIndexRoute
}

const UsersUserIdRouteChildren: UsersUserIdRouteChildren = {
  UsersUserIdTodosRoute: UsersUserIdTodosRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
  UsersUserIdAlbumsAlbumIdRoute: UsersUserIdAlbumsAlbumIdRoute,
  UsersUserIdPostsPostIdRoute: UsersUserIdPostsPostIdRoute,
  UsersUserIdAlbumsIndexRoute: UsersUserIdAlbumsIndexRoute,
}

const UsersUserIdRouteWithChildren = UsersUserIdRoute._addFileChildren(
  UsersUserIdRouteChildren,
)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRouteWithChildren
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRouteWithChildren,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersRoute: UsersRouteWithChildren,
  PostsPostIdRoute: PostsPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
